routes:
      '/':
            controller: main:index
      '/demo':
            controller: main:demo
      '/login':
            controller: user:login
      '/task/:int:':
                        controller: task:index
                        params:
                                id: 2